version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing prerequisites..."
      - aws --version
      - pip install --upgrade pip
      - pip install cfn-lint
      - echo "Environment setup complete."

  build:
    commands:
      - echo "Starting build phase..."
      - echo "Running CloudFormation linter..."
      - cfn-lint -t root.yaml || true

      - echo "Packaging CloudFormation templates..."
      - |
        if [ -z "$ARTIFACT_BUCKET" ]; then
          echo "ERROR: ARTIFACT_BUCKET variable is not set."
          exit 1
        fi
        echo "Using artifact bucket: $ARTIFACT_BUCKET"
        aws cloudformation package \
          --template-file root.yaml \
          --s3-bucket "$ARTIFACT_BUCKET" \
          --output-template-file packaged.yaml

      - echo "Verifying packaged.yaml exists..."
      - test -f packaged.yaml && echo "Packaging complete." || (echo "packaged.yaml missing!" && exit 1)

artifacts:
  files:
    - packaged.yaml
    - "*.yaml"

cache:
  paths:
    - '/root/.cache/pip/**/*'
