version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing prerequisites..."
      - aws --version
      - pip install --upgrade pip
      - pip install cfn-lint
      - |
        echo "Installing AWS Session Manager plugin (optional)..."
        curl -s "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/linux_64bit/session-manager-plugin.rpm" -o session-manager-plugin.rpm
        sudo dnf install -y session-manager-plugin.rpm || true
      - echo "Environment setup complete."

  build:
    commands:
      - echo "Starting build phase..."
      - echo "Running CloudFormation linter..."
      - cfn-lint -t root.yaml || true

      - echo "Packaging CloudFormation templates..."
      - aws cloudformation package \
          --template-file root.yaml \
          --s3-bucket "$ARTIFACT_BUCKET" \
          --output-template-file packaged.yaml

      - echo "Verifying packaged.yaml exists..."
      - test -f packaged.yaml && echo "Packaging complete." || (echo "packaged.yaml missing!" && exit 1)

artifacts:
  files:
    - packaged.yaml
    - "*.yaml"

cache:
  paths:
    - '/root/.cache/pip/**/*'
