AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Single-entry pipeline stack: creates CodePipeline + CodeBuild + IAM roles + S3 artifact bucket.
  Sources from GitHub via an existing CodeStar Connection and deploys nested stacks via CloudFormation.

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Source (GitHub via CodeStar)"
        Parameters:
          - CodeStarConnectionArn
          - GitHubRepo
          - BranchName
      - Label:
          default: "General"
        Parameters:
          - ProjectTag
    ParameterLabels:
      CodeStarConnectionArn:
        default: "CodeStar connection ARN (https://console.aws.amazon.com/codesuite/settings/connections)"
      GitHubRepo:
        default: "GitHub repository (owner/repo)"
      BranchName:
        default: "Repository branch"
      ProjectTag:
        default: "Project tag"

Parameters:
  CodeStarConnectionArn:
    Type: String
    Description: "Paste the ARN of your existing CodeStar connection (See URL above)."

  GitHubRepo:
    Type: String
    Description: "Full GitHub repository path (owner/repository)."

  BranchName:
    Type: String
    Default: main
    Description: "Repository branch to build from (default: main)."

  ProjectTag:
    Type: String
    Default: project
    Description: "Must be lower-case, numbers or both."

Resources:
  ########################################
  # S3 Artifact Bucket
  ########################################
  ArtifactBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      BucketName: !Sub "${ProjectTag}-artifacts-${AWS::AccountId}"
      VersioningConfiguration:
        Status: Suspended
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      Tags:
        - Key: Project
          Value: !Ref ProjectTag


  ########################################
  # IAM: CloudFormation Execution Role
  ########################################
  CloudFormationRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: cfn-exec-permissions
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ec2:*
                  - s3:*
                  - iam:*
                  - logs:*
                  - lambda:*
                  - sns:*
                  - sqs:*
                  - cloudwatch:*
                  - cloudformation:*
                  - ssm:GetParameter
                  - ssm:GetParameters
                  - ssm:GetParametersByPath
                  - elasticloadbalancing:*
                Resource: "*"
      Tags:
        - Key: Project
          Value: !Ref ProjectTag

  ########################################
  # IAM: CodeBuild Role
  ########################################
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: codebuild-logs-artifacts-cfn
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
              - Effect: Allow
                Action: s3:*
                Resource:
                  - !Sub "arn:${AWS::Partition}:s3:::${ArtifactBucket}"
                  - !Sub "arn:${AWS::Partition}:s3:::${ArtifactBucket}/*"
              - Effect: Allow
                Action:
                  - cloudformation:*
                  - iam:PassRole
                  - sts:AssumeRole
                Resource: "*"
      Tags:
        - Key: Project
          Value: !Ref ProjectTag

  ########################################
  # IAM: CodePipeline Role
  ########################################
  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: codepipeline-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:PutObject
                  - s3:GetBucketVersioning
                  - s3:ListBucket
                Resource:
                  - !Sub "arn:${AWS::Partition}:s3:::${ArtifactBucket}"
                  - !Sub "arn:${AWS::Partition}:s3:::${ArtifactBucket}/*"
              - Effect: Allow
                Action:
                  - cloudformation:CreateStack
                  - cloudformation:DeleteStack
                  - cloudformation:UpdateStack
                  - cloudformation:DescribeStacks
                  - cloudformation:DescribeStackEvents
                  - cloudformation:GetTemplate
                  - cloudformation:ListStacks
                  - cloudformation:GetTemplateSummary
                  - cloudformation:DescribeChangeSet
                  - cloudformation:ListChangeSets
                Resource: "*"
              - Effect: Allow
                Action:
                  - codebuild:StartBuild
                  - codebuild:BatchGetBuilds
                Resource: "*"
              - Effect: Allow
                Action: codestar-connections:UseConnection
                Resource: !Ref CodeStarConnectionArn
              - Effect: Allow
                Action: iam:PassRole
                Resource: "*"
      Tags:
        - Key: Project
          Value: !Ref ProjectTag

  ########################################
  # CodeBuild Project
  ########################################
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub "${ProjectTag}-build"
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:7.0
        Type: LINUX_CONTAINER
        PrivilegedMode: false
        EnvironmentVariables:
          - Name: PROJECT_NAME
            Type: PLAINTEXT
            Value: !Ref ProjectTag
          - Name: ARTIFACT_BUCKET
            Type: PLAINTEXT
            Value: !Ref ArtifactBucket
      Source:
        Type: CODEPIPELINE
      Cache:
        Type: NO_CACHE
      LogsConfig:
        CloudWatchLogs:
          Status: ENABLED
      Tags:
        - Key: Project
          Value: !Ref ProjectTag

  ########################################
  # CodePipeline Definition
  ########################################
  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Sub "${ProjectTag}-pipeline"
      RoleArn: !GetAtt CodePipelineRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactBucket
      Stages:
        - Name: Source
          Actions:
            - Name: GitHub_Source
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: "1"
              OutputArtifacts:
                - Name: SourceOutput
              Configuration:
                ConnectionArn: !Ref CodeStarConnectionArn
                FullRepositoryId: !Ref GitHubRepo
                BranchName: !Ref BranchName
                DetectChanges: true
        - Name: Build
          Actions:
            - Name: CodeBuild
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: BuildOutput
              Configuration:
                ProjectName: !Ref CodeBuildProject
        - Name: Deploy
          Actions:
            - Name: CloudFormation_Deploy
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: "1"
              InputArtifacts:
                - Name: BuildOutput
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: !Sub "${ProjectTag}-root"
                RoleArn: !GetAtt CloudFormationRole.Arn
                TemplatePath: "BuildOutput::packaged.yaml"
                Capabilities: CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND
      RestartExecutionOnUpdate: true
      Tags:
        - Key: Project
          Value: !Ref ProjectTag

Outputs:
  PipelineName:
    Description: Name of the created pipeline
    Value: !Ref Pipeline
  ArtifactBucketName:
    Description: Artifact bucket used by the pipeline
    Value: !Ref ArtifactBucket
  CodeStarConnectionUsed:
    Description: ARN of the CodeStar Connection used by the Source stage
    Value: !Ref CodeStarConnectionArn
