AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Root stack – Orchestrates VPC, EC2, and ALB via nested stacks.
  Fully dynamic: no hardcoded region, account, or role names.
  Uses pseudo parameters and stack outputs for automation.

Parameters:
  ProjectTag:
    Type: String
    Default: pipeline-project
    Description: Tag value to apply across all stacks.
  InstanceType:
    Type: String
    Default: t3.micro
  KeyName:
    Type: String
    Default: ""
    Description: Optional key pair (leave blank for SSM-only access).
  LatestAmiId:
    Type: "AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>"
    Default: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-6.1-x86_64
  VpcCidr:
    Type: String
    Default: 10.0.0.0/16
  PublicSubnetACidr:
    Type: String
    Default: 10.0.0.0/28
  PublicSubnetBCidr:
    Type: String
    Default: 10.0.0.16/28
  PrivateSubnetCidr:
    Type: String
    Default: 10.0.1.0/24

Resources:
  IamStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: iam.yaml

  VpcStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: vpc.yaml

  Ec2Stack:
    Type: AWS::CloudFormation::Stack
    DependsOn: VpcStack
    Properties:
      TemplateURL: ec2.yaml
      Parameters:
        VpcId: !GetAtt VpcStack.Outputs.VpcId
        SubnetId: !GetAtt VpcStack.Outputs.PrivateSubnet1
        SecurityGroupId: !GetAtt VpcStack.Outputs.PrivateSG
        LatestAmiId: !Ref LatestAmiId

  AlbStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: Ec2Stack
    Properties:
      TemplateURL: alb.yaml
      Parameters:
        VpcId: !GetAtt VpcStack.Outputs.VpcId
        TargetInstanceId: !GetAtt Ec2Stack.Outputs.InstanceId

Outputs:
  ProjectRegion:
    Value: !Ref AWS::Region
  ProjectAccountId:
    Value: !Ref AWS::AccountId
  VpcId:
    Value: !GetAtt VpcStack.Outputs.VPC1Id
  PrivateSubnetId:
    Value: !GetAtt VpcStack.Outputs.PrivateSubnet1AId
  InstanceId:
    Value: !GetAtt Ec2Stack.Outputs.InstanceId
  PrivateIp:
    Value: !GetAtt Ec2Stack.Outputs.PrivateIp
  AlbDNSName:
    Value: !GetAtt AlbStack.Outputs.AlbDNSName
